import { OptionPregunta } from "../models/optionPregunta";
import { Pregunta } from "../models/pregunta";

export const OpcionesData: OptionPregunta[] = [
        {
        title: 'Muy de acuerdo',
        checked: false,
        puntaje: 3,
        },
        {
        title: 'De acuerdo',
        checked: false,
        puntaje: 2,
        },
        {
        title: 'Moderadamente de acuerdo',
        checked: false,
        puntaje: 1,
        },
        {
        title: 'Ni de acuerdo ni en desacuerdo',
        checked: false,
        puntaje: 0,
        },
        {
        title: 'Moderadamente en desacuerdo',
        checked: false,
        puntaje: -1,
        },
        {
        title: 'En desacuerdo',
        checked: false,
        puntaje: -2,
        },
        {
        title: 'Muy en desacuerdo',
        checked: false,
        puntaje: -3,
        },
    ];

export const Cuestionario: Pregunta[] = [
        {
        id: 1,
        title: 'Los políticos deben estar cerca de la gente, escuchar y entender sus necesidades para darle lo que necesita.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#F7A334",
        Color:"#000000",
        },
        {
        id: 2,
        title: 'Si tuviera que elegir, diría que lo individual es más importante que lo colectivo.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "y",
        BG_Color: "#4BD6F7",
        Color:"#000000",
        },
        {
        id: 3,
        title: 'Si tenemos un gobierno fallido, no importa el plazo constitucional: hay que sacarlo cuanto antes.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#32F991",
        Color:"#000000",
        },
        {
        id: 4,
        title: 'En política, para algo existen las reglas de juego. Nunca es aceptable que los procedimientos se dejen de lado: hay que respetar las instituciones.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "y",
        BG_Color: "#FB2D11",
        Color:"#000000",
        },
        {
        id: 5,
        title: 'Es importante educar a nuestros niños en las tradiciones y limitar la influencia de productos culturales y tradiciones extranjeras.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#EEFF26",
        Color:"#000000",
        },
        {
        id: 6,
        title: 'Las decisiones políticas se toman más de acuerdo a los intereses de unos pocos poderosos que pensando en las necesidades de la gente.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#9F47FC ",
        Color:"#000000",
        },
        {
        id: 7,
        title: 'Muchas veces, conocer el pensamiento político de alguien permite saber si es una buena o mala persona.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#FC47C9",
        Color:"#000000",
        },
        {
        id: 8,
        title: 'Si tuviera que elegir, prefiero un liderazgo político “correcto” técnicamente, aburrido pero que administre bien, antes que uno que nos conmueva con nuevos sueños.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "y",
        BG_Color: "#C4C4C4",
        Color:"#000000",
        },
        {
        id: 9,
        title: 'El primer gol de Maradona a los ingleses (“la mano de Dios”) fue legítimo.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "y",
        BG_Color: "#367FFF",
        Color:"#000000",
        },
        {
        id: 10,
        title: 'En Democracia, hay libertad de expresión y yo puedo decir lo que quiera, siempre.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "y",
        BG_Color: "#000000",
        Color:"#ffffff",
        },
        {
        id: 11,
        title: 'Si tuviera que elegir, diría que la igualdad es más importante que la libertad.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#F7A334",
        Color:"#000000",
        },
        {
        id: 12,
        title: 'Los ricos deberían pagar mucho más impuestos que los que menos tienen.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#4BD6F7",
        Color:"#000000",
        },
        {
        id: 13,
        title: 'En general, la intervención del estado en el mercado distorsiona la economía y degrada el tejido productivo',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "x",
        BG_Color: "#32F991",
        Color:"#000000",
        },
        {
        id: 14,
        title: 'El sector privado gestiona mejor que el estado',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "x",
        BG_Color: "#FB2D11",
        Color:"#000000",
        },
        {
        id: 15,
        title: 'El Estado debe asistir económicamente a quienes han perdido el trabajo o se encuentran en situación de vulnerabilidad.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#EEFF26",
        Color:"#000000",
        },
        {
        id: 16,
        title: 'Se debería cobrar un arancel a quienes estudian en la universidad pública.',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "x",
        BG_Color: "#9F47FC",
        Color:"#000000",
        },
        {
        id: 17,
        title: 'La inmigración en Argentina debería estar más controlada e, idealmente, más limitada',
        opcionesPregunta: OpcionesData,
        QuestionScore: 1,
        Axis: "x",
        BG_Color: "#FC47C9",
        Color:"#000000",
        },
        {
        id: 18,
        title: 'Aquellas actividades económicas que dañan el medio ambiente deberían ser especialmente reguladas y en algunos casos prohibidas.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#C4C4C4",
        Color:"#000000",
        },
        {
        id: 19,
        title: 'Es importante fomentar y proteger la industria nacional.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#367FFF",
        Color:"#000000",
        },
        {
        id: 20,
        title: 'Industrias estratégicas como la nuclear o la militar no deberían estar en manos del sector privado.',
        opcionesPregunta: OpcionesData,
        QuestionScore: -1,
        Axis: "x",
        BG_Color: "#000000",
        Color:"#ffffff",
        },
    ];
